# Generated by Django 6.0.4 on 2026-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='medicina_tradicional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='plantas_medicinales',
            field=models.TextField(blank=True),
        ),
    ]
