# Generated by Django 6.0.4 on 2026-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_experiencia_medicina_tradicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='terapias_tradicionales',
            field=models.TextField(blank=True),
        ),
    ]
