# Generated by Django 6.0.4 on 2026-06-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_experiencia_terapias_tradicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
