# Generated by Django 6.0.4 on 2026-06-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_experiencia_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
