# Generated by Django 6.0.4 on 2026-06-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='medicina_tradicional',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='plantas_medicinales',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='terapias_tradicionales',
        ),
    ]
