# Generated by Django 6.0.4 on 2026-06-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_experiencia_medicina_tradicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
